"use client";

import React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { api } from "~/trpc/react";
import BrowseFeedList from "../browse/browse-feed/browse-feed-list";
import {
  ContentRating,
  useContentRating,
} from "../content-rating/content-rating";

export default function Featured() {
  const { contentRating } = useContentRating();

  const { data: featuredAdlibs, isLoading } =
    api.adlib.getFeaturedAdlibs.useQuery(
      {
        isPg: contentRating === ContentRating.PG,
      },
      {
        enabled: !!contentRating,
        refetchOnWindowFocus: false,
      },
    );

  return (
    <Card>
      <CardHeader>
        <CardTitle>Featured Adlibs</CardTitle>
        <CardDescription>
          View our featured adlibs generated by our users
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <p className="text-muted-foreground">Loading featured adlibs...</p>
        ) : !featuredAdlibs || featuredAdlibs.length === 0 ? (
          <p className="text-muted-foreground">No Featured Adlibs Available.</p>
        ) : (
          <BrowseFeedList adlibs={featuredAdlibs} />
        )}
      </CardContent>
    </Card>
  );
}
