"use client";

import React, { useEffect, useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { api } from "~/trpc/react";
import BrowseFeedList from "../browse/browse-feed/browse-feed-list";

const LOCAL_STORAGE_KEY = "contentRating";

export default function Featured() {
  const [contentRating, setContentRating] = useState<string>("pg");

  useEffect(() => {
    const storedRating = localStorage.getItem(LOCAL_STORAGE_KEY);
    if (storedRating) {
      setContentRating(storedRating);
    }
  }, []);

  const [featuredAdlibs] = api.adlib.getFeaturedAdlibs.useSuspenseQuery({
    isPg: contentRating === "pg",
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle>Featued Adlibs</CardTitle>
        <CardDescription>
          View our featured adlibs generated by our users
        </CardDescription>
      </CardHeader>
      <CardContent>
        {featuredAdlibs.length === 0 ? (
          <p className="text-muted-foreground">No Featued Adlibs Available.</p>
        ) : null}
        <BrowseFeedList adlibs={featuredAdlibs} />
      </CardContent>
    </Card>
  );
}
