"use client";

import React, { useState } from "react";
import { useAdlibsFeatured } from "../api/get-adlibs-featured-paginated";
import { useQueryClient } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import AdlibFeaturedList from "./adlib-featured-list/adlib-featured-list";
import Loader from "@/components/loader/loader";

const AdlibFeatured = () => {
  const [page] = useState<number>(1);
  const [size] = useState<number>(25);
  const [timestamp] = useState<Date>(new Date());
  const adlibsFeaturedQuery = useAdlibsFeatured({
    page,
    size,
    timestamp,
  });

  return (
    <Card className="pb-5">
      <header className="p-5">
        <h3 className="text-2xl font-semibold">Featured Adlibs</h3>
        <p className="text-muted-foreground">
          View our featured adlibs generated by other users
        </p>
      </header>
      {adlibsFeaturedQuery.isPending ? (
        <Loader className="p-5" />
      ) : (
        <AdlibFeaturedList adlibs={adlibsFeaturedQuery.data?.results ?? []} />
      )}
    </Card>
  );
};

export default AdlibFeatured;
