import Feed from "@/components/feed/Feed";
import { Card } from "@/components/ui/card";
import { useAdlibFeatured } from "./AdlibFeatured.hooks";
import AdlibFeaturedList from "./adlib-featured-list/AdlibFeaturedList";

const AdlibFeatured = () => {
  const { executable } = useAdlibFeatured();
  return (
    <Card className="p-5">
      <div>
        <h3 className="text-2xl font-semibold">Featured Adlibs</h3>
        <p className="text-zinc-600 dark:text-zinc-400">
          View our featured adlibs generated by our users.
        </p>
      </div>
      <Feed
        executable={executable}
        ListComponent={AdlibFeaturedList}
        endMessage={
          <p className="pt-5 px-4 font-semibold">No more data available</p>
        }
      />
    </Card>
  );
};

export default AdlibFeatured;
