import { MigrationInterface, QueryRunner } from "typeorm";

export class SetupTables1708884951986 implements MigrationInterface {
    name = 'SetupTables1708884951986'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "category" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(50) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "submission" ("id" SERIAL NOT NULL, "roundId" integer, "creatorId" integer, CONSTRAINT "PK_7faa571d0e4a7076e85890c9bd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "guestName" character varying(100), "judgeRoundsId" integer, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lobby" ("id" SERIAL NOT NULL, "roomCode" character varying(6) NOT NULL, "maxPlayers" integer NOT NULL DEFAULT '10', "creatorId" integer, CONSTRAINT "UQ_b02a7b091dd677ddb863a03126b" UNIQUE ("roomCode"), CONSTRAINT "UQ_b02a7b091dd677ddb863a03126b" UNIQUE ("roomCode"), CONSTRAINT "PK_0d9e681a820740df03d4ba784bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "game_session" ("id" SERIAL NOT NULL, "lobbyId" integer, CONSTRAINT "PK_58b630233711ccafbb0b2a904fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "round" ("id" SERIAL NOT NULL, "winningSubmissionId" integer, "gameSessionId" integer, CONSTRAINT "REL_b34f47db216d842c3f39d7518e" UNIQUE ("winningSubmissionId"), CONSTRAINT "PK_34bd959f3f4a90eb86e4ae24d2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adlib" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "oldId" character varying(24), "title" character varying(200) NOT NULL, "prompt" character varying(100) NOT NULL, "text" character varying NOT NULL, "isHidden" boolean NOT NULL DEFAULT false, "isPg" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "temperature" numeric(10,2) NOT NULL DEFAULT '0.7', "topP" numeric(10,2) NOT NULL DEFAULT '1', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "roundsId" integer, CONSTRAINT "UQ_af7e1d914f941cb5613020bcee4" UNIQUE ("oldId"), CONSTRAINT "PK_18ce95da5b60674008c6ddd70a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adlib_response_question" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "question" character varying NOT NULL, "answer" character varying NOT NULL, "order" integer NOT NULL, "adlibResponseId" integer, CONSTRAINT "PK_bfc4bb7eae0f1e8f5087dbb8936" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adlib_response" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "adlibId" integer, "submissionsId" integer, CONSTRAINT "PK_4561bf145faaa69003979da0062" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lobby_players_user" ("lobbyId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_df49e6fb5017ed44b63e6dad566" PRIMARY KEY ("lobbyId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_525ce3f57226c32ad6ac9ee3b6" ON "lobby_players_user" ("lobbyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9d48c9a253fe1a5f7cc3fd2ae" ON "lobby_players_user" ("userId") `);
        await queryRunner.query(`CREATE TABLE "adlib_categories_category" ("adlibId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_615f7e0f7266fcb48ecc1687585" PRIMARY KEY ("adlibId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14697d914e2651a6a5725db0d6" ON "adlib_categories_category" ("adlibId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4470930bd2d280816475edc91b" ON "adlib_categories_category" ("categoryId") `);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_d47ea70e5451399de0d8e136597" FOREIGN KEY ("roundId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_9cc58ba73cc153a85999c3dc77c" FOREIGN KEY ("creatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_216f999cb8cd5b9f15fc7395bde" FOREIGN KEY ("judgeRoundsId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lobby" ADD CONSTRAINT "FK_c9d62061273375bd10354262eba" FOREIGN KEY ("creatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_session" ADD CONSTRAINT "FK_12680abb1f0b56879f0dd48edb5" FOREIGN KEY ("lobbyId") REFERENCES "lobby"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "round" ADD CONSTRAINT "FK_b34f47db216d842c3f39d7518e0" FOREIGN KEY ("winningSubmissionId") REFERENCES "submission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "round" ADD CONSTRAINT "FK_ec500fa3aaa596f0f039215218a" FOREIGN KEY ("gameSessionId") REFERENCES "game_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adlib" ADD CONSTRAINT "FK_9134d4fb031adfc19df168a2240" FOREIGN KEY ("roundsId") REFERENCES "round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adlib_response_question" ADD CONSTRAINT "FK_1bc6c3e97c736e6b427cd487f76" FOREIGN KEY ("adlibResponseId") REFERENCES "adlib_response"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adlib_response" ADD CONSTRAINT "FK_85840b342c4b4ffb3bc4abf0497" FOREIGN KEY ("adlibId") REFERENCES "adlib"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adlib_response" ADD CONSTRAINT "FK_9e9299cb02f7900cf5dee14ba4c" FOREIGN KEY ("submissionsId") REFERENCES "submission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lobby_players_user" ADD CONSTRAINT "FK_525ce3f57226c32ad6ac9ee3b69" FOREIGN KEY ("lobbyId") REFERENCES "lobby"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lobby_players_user" ADD CONSTRAINT "FK_c9d48c9a253fe1a5f7cc3fd2ae2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "adlib_categories_category" ADD CONSTRAINT "FK_14697d914e2651a6a5725db0d6b" FOREIGN KEY ("adlibId") REFERENCES "adlib"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "adlib_categories_category" ADD CONSTRAINT "FK_4470930bd2d280816475edc91b1" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "adlib_categories_category" DROP CONSTRAINT "FK_4470930bd2d280816475edc91b1"`);
        await queryRunner.query(`ALTER TABLE "adlib_categories_category" DROP CONSTRAINT "FK_14697d914e2651a6a5725db0d6b"`);
        await queryRunner.query(`ALTER TABLE "lobby_players_user" DROP CONSTRAINT "FK_c9d48c9a253fe1a5f7cc3fd2ae2"`);
        await queryRunner.query(`ALTER TABLE "lobby_players_user" DROP CONSTRAINT "FK_525ce3f57226c32ad6ac9ee3b69"`);
        await queryRunner.query(`ALTER TABLE "adlib_response" DROP CONSTRAINT "FK_9e9299cb02f7900cf5dee14ba4c"`);
        await queryRunner.query(`ALTER TABLE "adlib_response" DROP CONSTRAINT "FK_85840b342c4b4ffb3bc4abf0497"`);
        await queryRunner.query(`ALTER TABLE "adlib_response_question" DROP CONSTRAINT "FK_1bc6c3e97c736e6b427cd487f76"`);
        await queryRunner.query(`ALTER TABLE "adlib" DROP CONSTRAINT "FK_9134d4fb031adfc19df168a2240"`);
        await queryRunner.query(`ALTER TABLE "round" DROP CONSTRAINT "FK_ec500fa3aaa596f0f039215218a"`);
        await queryRunner.query(`ALTER TABLE "round" DROP CONSTRAINT "FK_b34f47db216d842c3f39d7518e0"`);
        await queryRunner.query(`ALTER TABLE "game_session" DROP CONSTRAINT "FK_12680abb1f0b56879f0dd48edb5"`);
        await queryRunner.query(`ALTER TABLE "lobby" DROP CONSTRAINT "FK_c9d62061273375bd10354262eba"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_216f999cb8cd5b9f15fc7395bde"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_9cc58ba73cc153a85999c3dc77c"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_d47ea70e5451399de0d8e136597"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4470930bd2d280816475edc91b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14697d914e2651a6a5725db0d6"`);
        await queryRunner.query(`DROP TABLE "adlib_categories_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9d48c9a253fe1a5f7cc3fd2ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_525ce3f57226c32ad6ac9ee3b6"`);
        await queryRunner.query(`DROP TABLE "lobby_players_user"`);
        await queryRunner.query(`DROP TABLE "adlib_response"`);
        await queryRunner.query(`DROP TABLE "adlib_response_question"`);
        await queryRunner.query(`DROP TABLE "adlib"`);
        await queryRunner.query(`DROP TABLE "round"`);
        await queryRunner.query(`DROP TABLE "game_session"`);
        await queryRunner.query(`DROP TABLE "lobby"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "submission"`);
        await queryRunner.query(`DROP TABLE "category"`);
    }

}
