import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Card from "../../Card/Card";
import Lib from "../../../api/Lib";
import ApiErrorHandler from "../../../errors/ApiErrorHandler";

const Libs = () => {
  const [libs, setLibs] = useState([]);
  const [error, setError] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isEnd, setIsEnd] = useState(false);
  const [page, setPage] = useState(1);
  const [timestamp] = useState(new Date());
  const pagination = 20;

  const getFood = async (isStart) => {
    try {
      setIsLoading(true);
      setError(null);
      const formattedDate = dayjs(timestamp).format("YYYY-MM-DD");
      const response = await Lib.get(
        formattedDate,
        page,
        pagination,
        "featured"
      );
      return response.data;
    } catch (e) {
      setError(ApiErrorHandler.handleRequestResponse(e));
    } finally {
      setIsLoading(false);
    }
  };

  const loadMoreFood = async () => {
    try {
      setIsLoading(true);
      setError(null);
      const response = await getFood();
      if (response.results) {
        setLibs((curr) => [...curr, ...response.results]);
      }
      setPage((curr) => response?.page ?? curr + 1);
      if (response.page >= response.totalPage) {
        setIsEnd(true);
      }
    } catch (e) {
      setError(e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    (async () => {
      try {
        setIsEnd(false);
        const response = await getFood(true);
        setLibs(response ? response?.results : []);
        setPage(response ? response?.page : 1);
        if (response && response.page >= response.totalPage) {
          setIsEnd(true);
        }
      } catch (e) {
        setError(e);
      }
    })();
  }, []);

  return (
    <Card className="flex flex-col gap-3">
      <div>
        <h3 className="text-2xl font-semibold">Featured Ad-libs</h3>
        <p className="text-zinc-400">
          View our featured Ad-Libs generated by our users.
        </p>
      </div>

      <ul>
        {libs.map((lib) => {
          return (
            <li key={lib._id}>
              <div className="border border-zinc-600 text-white p-5 rounded-lg">
                <h6 className="text-xl font-semibold">The Magic Wand...</h6>
                <Link
                  to="view"
                  className="p-3 rounded border border-zinc-600 text-white inline-block mt-6 hover:bg-zinc-900 active:bg-zinc-800 duration-200 ease-out"
                >
                  Go To Ad-Lib
                </Link>
              </div>
            </li>
          );
        })}
      </ul>
    </Card>
  );
};

export default Libs;
