name: End to End Tests


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress install
        uses: cypress-io/github-action@v7
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v6
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download the build folder
        uses: actions/download-artifact@v7
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          browser: chrome